eureka:
  client:
    serviceUrl:
      defaultZone:  http://localhost:8761/eureka/
  instance:
    prefer-ip-address:  true

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name:  com.mysql.cj.jdbc.Driver
    username: root
    password: root
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      timeBetweenEvictionRunsMillis:  60000
      stat-view-servlet:
        url-pattern:  "/druid/*"
        allow: 127.0.0.1
        reset-enable: false
        login-username: root
        login-password: root

mybatis-plus:
  mapper-locations: classpath*:cn/itsource/hrm/mapper/*Mapper.xml
  type-aliases-package: cn.itsource.hrm.domain,cn.itsource.hrm.query

logging:
  level:
    cn.itsource.hrm:  debug